/**
 * Decides which authorities in a memorial carry a [VERIFY] mark, and restores
 * citations the advocate supplied.
 *
 * WHY THIS IS NOT LEFT TO THE MODEL
 * Asked to self-assess, it marked all six authorities in a test memorial as
 * verify:false — full confidence — including two obscure Karnataka Law Journal
 * citations that could not be confirmed to exist. That is the same overconfidence
 * that produced the fabrications this exists to stop: an earlier draft cited
 * "Suryadev Rai v. Ram Chander Rai, (2008) 12 SCC 1" when the case is Surya Dev
 * Rai v. Ram Chander Rai, (2003) 6 SCC 675, and two further authorities in that
 * draft could not be traced at all.
 *
 * So the flag is set here, deterministically: anything the advocate did not
 * supply is marked for verification whatever the model claims.
 *
 * AND THE MODEL DOES NOT GET TO REWRITE WHAT IT WAS HANDED
 * Given "Surya Dev Rai v. Ram Chander Rai, (2003) 6 SCC 675" as one of the
 * advocate's own selected authorities, it returned "(1993) 6 SCC 675" — silently
 * changing the year of a case the advocate had chosen and already verified. An
 * advocate's own citation is restored verbatim.
 *
 * Flagging is limited to CASE groups on purpose. Fabrication risk lives in
 * reporter references — volume, year, page. A statute is a named instrument with
 * a section number, cheap to check and rarely hallucinated wholesale. Flagging
 * "Code of Civil Procedure, 1908 — Section 9" next to a doubtful case citation
 * would teach advocates to ignore the marker, and then it protects nobody.
 */

const CASE_GROUPS = ['cases', 'internationalCases'];

const norm = s => String(s || '').toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();

/**
 * @param {object} indexOfAuthorities  Mutated in place.
 * @param {Array}  advocateAuthorities The advocate's Authority Armory picks.
 * @returns {{flagged:number, restored:number}}
 */
function applyCitationGuard(indexOfAuthorities, advocateAuthorities) {
  const ioa = indexOfAuthorities;
  if (!ioa || typeof ioa !== 'object') return { flagged: 0, restored: 0 };
  const supplied = Array.isArray(advocateAuthorities) ? advocateAuthorities : [];
  let flagged = 0, restored = 0;

  const findSupplied = name => supplied.find(a => {
    const n = norm(name), an = norm(a.name || a.case);
    return n && an && (n.includes(an) || an.includes(n));
  });

  for (const group of CASE_GROUPS) {
    if (!Array.isArray(ioa[group])) continue;
    for (const entry of ioa[group]) {
      if (!entry || typeof entry !== 'object') continue;

      const own = findSupplied(entry.name);
      if (own) {
        entry.source = 'advocate';
        if (own.citation && entry.citation !== own.citation) {
          console.warn(`[CITATION GUARD] Restored "${entry.name}": model returned `
            + `"${entry.citation}", advocate supplied "${own.citation}".`);
          entry.citation = own.citation;
          restored++;
        }
        continue;
      }

      entry.source = 'suggested';
      if (entry.verify !== true) {
        entry.verify = true;
        entry.citationNote = [entry.citationNote,
          'Generated by MootCoach and not verified against any reporter — check before relying on it.']
          .filter(Boolean).join(' ');
        flagged++;
      }
    }
  }

  if (flagged || restored) {
    console.log(`[CITATION GUARD] flagged ${flagged} model-supplied authorities, `
      + `restored ${restored} advocate citations.`);
  }
  return { flagged, restored };
}

module.exports = { applyCitationGuard, CASE_GROUPS };
